### ISSUE TITLE
打开终端输入代码并下载后报错

### ISSUE THREAD

**Issue by Tianseen** [akbaryahya/DockerGC#11]
SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at main (/usr/local/lib/node_modules/json/lib/json.js:1365:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/json/lib/json.js:1764:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
undefined:3
this.GameServer.DispatchServerDatabaseUrl=''mongodb://db:27017''
                                            ^^^^^^^

SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at main (/usr/local/lib/node_modules/json/lib/json.js:1365:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/json/lib/json.js:1764:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
undefined:3
this.DispatchServer.PublicIp=''localhost''
                               ^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at main (/usr/local/lib/node_modules/json/lib/json.js:1365:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/json/lib/json.js:1764:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
undefined:3
this.GameServer.PublicIp=''localhost''
                           ^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at main (/usr/local/lib/node_modules/json/lib/json.js:1365:27)
    at Object.<anonymous> (/usr/local/lib/node_modules/json/lib/json.js:1764:5)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
VERSION  config.json  data  grasscutter.jar  keys  keystore.p12  logs  proxy.py  proxy_config.py  resources
[19:11:15] [INFO] Place a copy of 'BinOutput' and 'ExcelBinOutput' in the resources folder.

**Comment by akbaryahya** [comment]
what version is this? you have to do 2 lines before starting the server if you don't have a datebase in windows running/outside docker
