### ISSUE TITLE
Load language file failed.

### ISSUE THREAD

**Issue by rama291041610** [akbaryahya/DockerGC#14]
I build the project on the image `siakbary/dockergc:debian-dev-4.8`, but it always restarts.

error log:
```
08:44:01] [INFO] load file en.json
[08:44:01] [INFO] fallback to en.json
[08:44:01] [WARN] Failed to load language file: en.json
java.lang.NullPointerException: null
	at java.base/java.io.Reader.<init>(Reader.java:168)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:111)
	at emu.grasscutter.utils.Utils.readFromInputStream(Utils.java:268)
	at emu.grasscutter.utils.Language.<init>(Language.java:59)
	at emu.grasscutter.utils.Language.getLanguage(Language.java:23)
	at emu.grasscutter.Grasscutter.loadLanguage(Grasscutter.java:158)
	at emu.grasscutter.Grasscutter.<clinit>(Grasscutter.java:63)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "object" is null
	at emu.grasscutter.utils.Language.get(Language.java:89)
	at emu.grasscutter.utils.Language.translate(Language.java:33)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:89)
````
Now, `en.json` can't be found.
https://github.com/Grasscutters/Grasscutter/tree/stable/src/main/resources/languages

Besides, hope to add an argument to set language.

**Comment by rama291041610** [comment]
error log:
```
08:44:01] [INFO] load file en.json
[08:44:01] [INFO] fallback to en.json
[08:44:01] [WARN] Failed to load language file: en.json
java.lang.NullPointerException: null
	at java.base/java.io.Reader.<init>(Reader.java:168)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:111)
	at emu.grasscutter.utils.Utils.readFromInputStream(Utils.java:268)
	at emu.grasscutter.utils.Language.<init>(Language.java:59)
	at emu.grasscutter.utils.Language.getLanguage(Language.java:23)
	at emu.grasscutter.Grasscutter.loadLanguage(Grasscutter.java:158)
	at emu.grasscutter.Grasscutter.<clinit>(Grasscutter.java:63)
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "object" is null
	at emu.grasscutter.utils.Language.get(Language.java:89)
	at emu.grasscutter.utils.Language.translate(Language.java:33)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:89)
````

**Comment by akbaryahya** [comment]
https://github.com/akbaryahya/Grasscutter/commit/2de92cdf62df70cdbfddb5c9fdefb92d33df0995 it should have been updated 12 hours ago before 4.9 but if it doesn't work try a new version, yep for argument i'll try to add it in the next version
