### ISSUE TITLE
MongoDB works upon first server startup, but stops working afterwards

### ISSUE THREAD

**Issue by vhcrack** [akbaryahya/DockerGC#20]
It worked when I launched DockerGC for the first time, but, I restarted my Ubuntu server and tried to start it up again which resulted in this error:
`Exception in monitor thread while connecting to server db:27017
com.mongodb.MongoSocketException: db
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:211)
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:75)
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65)
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:143)
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:188)
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:144)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.UnknownHostException: db
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
        at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:887)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1509)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1367)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1301)
        at com.mongodb.ServerAddress.getSocketAddresses(ServerAddress.java:203)
        ... 6 common frames omitted`

I had already checked that mongod was running so I don't understand why it isn't working.

**Comment by vhcrack** [comment]
Closing this issue
